#!/usr/bin/env bash
# adapter.sh - Adapter for Antigravity (Gemini CLI)
# Generates .agents/ structure with MCP, skills, agents and AGENTS.md
#
# Based on ANTIGRAVITY-GUIDE.md
#
# Called by sdd-init.sh with:
#   bash adapter.sh --org $ORG --project $PROJECT --ide-dir .agents --script-dir $SCRIPT_DIR --pat64 $PAT64 --github-pat $GITHUB_PAT --stitch-key $STITCH_KEY

set -e

# --- Parse args ---
ORG=""
PROJECT=""
IDE_DIR=""
SCRIPT_DIR=""
PAT64=""
GITHUB_PAT=""
STITCH_KEY=""
FORCE=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --org)        ORG="$2"; shift 2 ;;
    --project)    PROJECT="$2"; shift 2 ;;
    --ide-dir)    IDE_DIR="$2"; shift 2 ;;
    --script-dir) SCRIPT_DIR="$2"; shift 2 ;;
    --pat64)      PAT64="$2"; shift 2 ;;
    --github-pat) GITHUB_PAT="$2"; shift 2 ;;
    --stitch-key) STITCH_KEY="$2"; shift 2 ;;
    --force)      FORCE=true; shift ;;
    *) shift ;;
  esac
done

echo "   Generating Antigravity (.agents/) structure..."

PROJECT_ROOT="$(pwd)"
if command -v cygpath >/dev/null 2>&1; then
  PROJECT_ROOT="$(cygpath -m "$PROJECT_ROOT")"
fi

# --- Detect codebase-memory binary ---
CBM_BIN=""
if [ -f "$HOME/.local/bin/codebase-memory-mcp.exe" ]; then
  CBM_BIN="$HOME/.local/bin/codebase-memory-mcp.exe"
elif [ -f "$HOME/.local/bin/codebase-memory-mcp" ]; then
  CBM_BIN="$HOME/.local/bin/codebase-memory-mcp"
fi
if [ -n "$CBM_BIN" ] && command -v cygpath >/dev/null 2>&1; then
  CBM_BIN="$(cygpath -m "$CBM_BIN")"
fi

# --- 1. Create directory structure ---
mkdir -p .agents/agents .agents/skills

# --- 2. Generate mcp_config.json (bulletproof valid JSON via node) ---
node - "$ORG" "$PROJECT" "$PAT64" "$PROJECT_ROOT" "$CBM_BIN" << 'NODE_EOF'
const fs = require('fs');
const [org, project, pat64, projectRoot, cbmBin] = process.argv.slice(2);

const config = {
  mcpServers: {
    "azure-devops": {
      command: "npx",
      args: ["-y", "@azure-devops/mcp", org, "--authentication", "pat"],
      env: {
        ...(pat64 ? { PERSONAL_ACCESS_TOKEN: pat64 } : {}),
        AZURE_DEVOPS_DEFAULT_PROJECT: project
      }
    },
    "sequential-thinking": {
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-sequential-thinking"]
    },
    "context7": {
      command: "npx",
      args: ["-y", "@upstash/context7-mcp@latest"]
    },
    "github": {
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-github"],
      env: {}
    },
    "server-memory": {
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-memory"],
      env: {
        MEMORY_FILE_PATH: `${projectRoot}/.sdd-memory/memory.jsonl`
      }
    },
    "playwright": {
      command: "npx",
      args: ["-y", "@playwright/mcp@latest"]
    },
    "stitch": {
      command: "npx",
      args: ["-y", "@google/stitch-sdk"],
      env: {}
    }
  }
};

if (cbmBin) {
  config.mcpServers["codebase-memory-mcp"] = {
    command: cbmBin,
    args: []
  };
}

fs.writeFileSync('.agents/mcp_config.json', JSON.stringify(config, null, 2) + '\n');
NODE_EOF

echo "   OK mcp_config.json generated (7 MCPs + codebase-memory-mcp if installed)"

# --- 3. ALWAYS-ON rules (.agents/rules/) ---
# Antigravity loads skills ON DEMAND (only name+description by default).
# Rules that must be active from the first message go here instead.
mkdir -p .agents/rules
rm -f .agents/AGENTS.md  # legacy location (not in Antigravity's rule discovery path)

write_always_on() {
  # $1 = output file, $2.. = source rule names
  local out="$1"; shift
  printf '%s\n' '---' 'trigger: always_on' '---' '' > "$out"
  for rule in "$@"; do
    if [ -f "$SCRIPT_DIR/core/rules/$rule.md" ]; then
      cat "$SCRIPT_DIR/core/rules/$rule.md" >> "$out"
      printf '\n---\n\n' >> "$out"
    fi
  done
}

write_always_on .agents/rules/sdd-tool-protocol.md "tool-protocol"
write_always_on .agents/rules/sdd-precheck.md "precheck"
write_always_on .agents/rules/sdd-workflow.md "workflow-router" "spec-integration" "artifact-storage" "change-propagation" "spec-structure-gate"

cat > .agents/rules/sdd-core.md << 'CORE_EOF'
---
trigger: always_on
---

# SDD Standard — Core (always on)

> Auto-generated by sdd-init.sh. Do not edit manually.
> RQE defines the QUÉ functional. Development conserves the CÓMO technical.

## Hard Gates (non-negotiable)
1. AI proposes, human approves — NEVER execute without explicit approval
2. One spec at a time — finish before starting another
3. No auto-deploy prod — production requires explicit approval
4. No auto-merge PRs — every PR requires human review
5. Templates mandatory — never create specs without templates
6. AB# in every commit
7. Memory-first — server-memory before files, codebase-memory before grep (see sdd-tool-protocol)
8. No editing protected files (.agents/mcp_config.json, .sdd-config.json, .sdd-credentials.json, etc.)
9. Bug != Feature — different flows
10. Requirements from Functional Package (primary) or ADO (fallback)

## MCP checkpoints (MANDATORY — full detail in sdd-tool-protocol)
- Session start: server-memory read → report "🧠 Memoria: …"; codebase-memory index check → report "🗺️ Grafo: …"
- Before reading code: codebase-memory search_graph + get_code_snippet (NOT grep, NOT whole files)
- Before changing a function: codebase-memory trace_path inbound
- After decision / bug fix / correction / convention: server-memory create_entities → report "🧠 Guardado: …"

## Bug fixes (MANDATORY — activate skill bug-fix-protocol)
A bug is NOT fixed without evidence. Phases: investigate (ADO + memory + graph + git history + similar resolved bugs)
→ reproduce with failing test → impact analysis (callers, risk) → minimal fix → verify (regression, local smoke test
with Playwright, acceptance criteria) → evidence report in PR → deployment verification in DEV and QA → write BugFix to memory.
Reopened bug → write Correction, restart from investigation.

## WI States
To Do → In Progress → Fixed → In Testing → Done
Reopen: QA finds issues. On Hold/Fix Later: human decision.
Acceptance: QA corte PBI active. Test Passed/QA Passed: HU/E2E validated by QA.
Agent only: To Do→In Progress, In Progress→Fixed, Reopen→In Progress
Agent NEVER: Done, In Testing, Reopen, On Hold, Fix Later, Acceptance, Test Passed, QA Passed

## QA Corte and releases (activate skill qa-corte-workflow)
- Detect active cortes at session start (PBIs with 'corte al' in title, state=Acceptance) — corte bugs first
- NEVER merge develop→qa or qa→main directly — audit scope, use release/corte-DD-MM-YYYY or release/prod-DD-MM-YYYY
- Post audit trail comment on ADO PBIs after each release. Tag vX.Y.Z after prod merge (with approval)

## Features & Specs (MANDATORY — activate skill spec-generation-protocol)
Supports Forward (new), Reverse (existing code/as-built), and Hybrid (extending existing modules).
NEVER code without approved requirements.md, design.md, and tasks.md.

## Skills to activate on demand
bug-fix-protocol · qa-corte-workflow · spec-generation-protocol · azure-devops-workflow · git-conventions · protected-files · token-optimization
CORE_EOF

echo "   OK 4 always-on rules generated (.agents/rules/)"

# --- 4. Procedural rules as skills (on demand) ---
SKILL_RULES=("bug-fix-protocol" "qa-corte-workflow" "spec-generation-protocol" "azure-devops-workflow" "git-conventions" "protected-files" "token-optimization")

for rule in "${SKILL_RULES[@]}"; do
  mkdir -p ".agents/skills/$rule"
  if [ -f "$SCRIPT_DIR/core/rules/$rule.md" ]; then
    {
      printf '%s\n' '---' "name: $rule" "description: $(head -1 "$SCRIPT_DIR/core/rules/$rule.md" | sed 's/^# //')" '---' ''
      cat "$SCRIPT_DIR/core/rules/$rule.md"
    } > ".agents/skills/$rule/SKILL.md"
  fi
done
# Remove skills that are now always-on rules (avoid duplicates from older installs)
rm -rf .agents/skills/precheck .agents/skills/tool-protocol
echo "   OK ${#SKILL_RULES[@]} rules converted to skills"

# --- 4b. Hook: inject MCP checklist at the start of each session ---
mkdir -p .agents/hooks
cat > .agents/hooks/sdd-mcp-reminder.js << 'HOOK_EOF'
// SDD Standard — PreInvocation hook. Injects the MCP checklist on the first model call.
let raw = '';
process.stdin.on('data', (c) => (raw += c));
process.stdin.on('end', () => {
  let input = {};
  try { input = JSON.parse(raw || '{}'); } catch (e) {}
  if ((input.invocationNum || 0) > 1) { process.stdout.write('{}'); return; }
  const msg = [
    'SDD MCP checklist (mandatory, see sdd-tool-protocol):',
    '1. server-memory: search_nodes/read_graph -> report "Memoria: N entidades"',
    '2. codebase-memory: list_projects -> index_repository if missing/stale -> report "Grafo: ..."',
    '3. Code discovery: search_graph + get_code_snippet BEFORE grep or reading files',
    '4. Before changing code: trace_path inbound (callers)',
    '5. Bug? activate skill bug-fix-protocol. Write BugFix/Decision/Correction to server-memory when done',
  ].join('\n');
  process.stdout.write(JSON.stringify({ injectSteps: [{ ephemeralMessage: msg }] }));
});
HOOK_EOF

cat > .agents/hooks.json << 'HOOKS_EOF'
{
  "sdd-mcp-reminder": {
    "PreInvocation": [
      { "type": "command", "command": "node hooks/sdd-mcp-reminder.js", "timeout": 10 }
    ]
  }
}
HOOKS_EOF

echo "   OK hooks.json generated (MCP checklist at session start)"

# --- 5. Generate 3 agents with Gemini frontmatter ---

# sdd-router
cat > .agents/agents/sdd-router.md << ROUTER_EOF
---
name: sdd-router
description: SDD workflow router — routes requests to skills, enforces lifecycle gates, role validation, and post-commit integrations.
mainAgent: true
subagent: false
model: pro
tools:
  - view_file
  - grep_search
  - run_command
commandExecutionPolicy: auto
skills:
  - skills/bug-fix-protocol
  - skills/qa-corte-workflow
  - skills/azure-devops-workflow
  - skills/git-conventions
  - skills/protected-files
  - skills/token-optimization
---

# SDD Router

You are the SDD router agent. Role: developer.

## On startup (automatic)
1. Run precheck (6 mandatory steps)
2. Lifecycle mode detection: Brownfield (existing code) or Greenfield (new repo from scratch). If Greenfield, route to project inception, stack architecture and Forward specs (Wave 0 scaffolding).
3. Load server-memory (decisions, conventions, corrections)
4. Read Azure DevOps → show assigned items from current sprint
5. Check for active QA corte (PBIs with 'corte al' in title, state=Acceptance)
6. Detect type: Feature, Bug, or QA Corte
7. Route to sdd-plan (analysis) or sdd-build (implementation)

## Routing
- Analysis/planning → sdd-plan agent (read-only, proposes)
- Implementation → sdd-build agent (edits with approval)
- Switch between agents: Tab

## After finishing an AB#
- Read Azure DevOps → check for remaining assigned items in To Do or Reopen
- If items remain: present them and ask to continue
- DO NOT say goodbye without offering remaining work
ROUTER_EOF

# sdd-plan
cat > .agents/agents/sdd-plan.md << PLAN_EOF
---
name: sdd-plan
description: SDD plan agent — read-only analysis, lifecycle position, gate checking, next-step planning.
mainAgent: true
subagent: true
model: pro
tools:
  - view_file
  - grep_search
commandExecutionPolicy: off
skills:
  - skills/spec-generation-protocol
  - skills/bug-fix-protocol
  - skills/qa-corte-workflow
  - skills/azure-devops-workflow
---

# SDD Plan Agent

You are the SDD plan agent. Role: developer. READ-ONLY.

## On startup (automatic)
1. Run precheck (6 mandatory steps — see sdd-precheck rule)
2. Lifecycle mode detection: if Greenfield (no code), offer Greenfield Inception (Architecture & Stack) or MVP Spec (with Wave 0 Scaffolding). Do NOT offer bug fix options.
3. server-memory (MANDATORY): load Decisions, Conventions, Corrections, BugFixes → report "🧠 Memoria: ..."
4. codebase-memory (MANDATORY): verify index → report "🗺️ Grafo: ..."
5. Read Azure DevOps → show assigned items from current sprint
6. Check for active QA corte
7. Detect type: Feature, Bug, or QA Corte
8. Detect phase of work

## For features (skill spec-generation-protocol)
Supports three modes depending on request:

Mode 1: Forward Spec (New Feature)
- Detect entry point: Document/File (Channel A), Business Elicitation Interview (Channel B), Functional Package or ADO WI (Channel C)
- Step 1: Propose requirements.md (EARS notation, acceptance criteria, NFRs) -> wait for approval
- Step 2: Propose design.md (architecture, component diagram, data model, APIs) -> wait for approval
- Step 3: Propose tasks.md (waves, dependencies, <4h per task) -> wait for approval

Mode 2: Reverse Spec (Existing/Legacy Code Documentation)
- Mine code using codebase-memory: search_graph and trace_path
- Mine Git history: git log -- <files>, git log --grep="AB#", and git blame for rationale behind formulas and constants
- Step 1: Draft requirements.md (As-Built) capturing existing business logic in EARS notation with git evidence
- Step 2: Draft design.md (As-Built) with real Mermaid diagrams, DB schemas, and API contracts
- Step 3: Draft tasks.md focusing on gaps (missing unit/E2E tests, technical debt, error handling)

Mode 3: Hybrid Spec (Extending Existing Modules)
- Map existing foundation (tables, endpoints, enums) as dependencies
- Run Forward Spec (Mode 1) for the new sub-feature only

## For bugs (skill bug-fix-protocol, Phases 1 and 3, read-only)
- Investigate: ADO WI + repro steps + linked WIs + resolved Bugs in the same module
- Memory: server-memory search_nodes for the module → Corrections, BugFixes
- Locate: codebase-memory search_graph + get_code_snippet (NOT grep)
- History: git log / git blame on affected files → regression or pre-existing?
- Impact: codebase-memory trace_path inbound → callers, affected features, risk BAJO/MEDIO/ALTO
- Propose: root cause, fix plan, reproduction test, regression test plan, deployment requirements
- If root cause is not clear → say so and propose a diagnostic step. NEVER guess

## For QA Corte (testing cut cycle)
- Query ADO for active cortes (PBIs with 'corte al' in title, state=Acceptance)
- Show corte summary: PBIs, pending bugs, HU/E2E validation status
- For each pending bug: analyze code and propose fix plan (read-only)
- Identify dependencies between corte bugs
- Highlight blocking bugs (bugs that block HU/E2E from reaching Test Passed)

## After finishing an AB# (when user returns from sdd-build)
- Read Azure DevOps → check for remaining assigned items in To Do or Reopen
- Automatically present remaining items
- DO NOT say goodbye without offering to continue

## What NEVER to present as options
- "Explore codebase" → do it automatically (codebase-memory)
- "Load context into memory" → do it automatically (server-memory)
- "View project status" → do it automatically (precheck)
- In Greenfield mode (project from scratch): do NOT offer Bug or QA Corte options (no code exists). ONLY offer:
  1. Project Inception (Stack & Architecture selection)
  2. Forward Spec with Wave 0 Scaffolding (requirements/design/tasks)
- In Brownfield mode (existing code is present), present WORK options:
  1. Feature — propose design + architecture + tasks
  2. Bug — analyze code and propose fix plan
  3. QA Corte — show summary and propose working on corte bugs

## HARD GATES
1. One spec at a time
2. Templates mandatory
3. Memory-first
4. Bug != Feature
5. Requirements from Functional Package or ADO
6. Read linked WIs (Data Dictionary, Structure, Business Rule)
7. State transitions — plan agent does NOT move WI states
8. DO NOT move WIs to Acceptance, Test Passed, or QA Passed (QA only)
PLAN_EOF

# sdd-build
cat > .agents/agents/sdd-build.md << BUILD_EOF
---
name: sdd-build
description: SDD build agent — lifecycle gates, one-file-at-a-time, explicit approval, role enforcement.
mainAgent: true
subagent: true
model: pro
tools:
  - view_file
  - replace_file_content
  - run_command
  - manage_task
commandExecutionPolicy: eager
skills:
  - skills/spec-generation-protocol
  - skills/bug-fix-protocol
  - skills/qa-corte-workflow
  - skills/azure-devops-workflow
  - skills/git-conventions
  - skills/protected-files
  - skills/token-optimization
---

# SDD Build Agent

You are the SDD build agent. Role: developer.

## HARD GATES (NEVER violate)
1. AI proposes, human approves — NEVER execute without explicit approval
2. One spec at a time — do not mix features/bugs
3. No auto-deploy prod
4. No auto-merge PRs
5. Templates mandatory — NEVER create specs without using specs/_templates/
6. AB# in every commit
7. Memory-first — server-memory before files, codebase-memory before grep
8. No editing protected files
9. Bug != Feature — Bug: direct fix. Feature: design + tasks
10. Requirements from Functional Package (primary) or ADO (fallback)

## On startup (automatic)
1. Run precheck (6 mandatory steps — see sdd-precheck rule)
2. Lifecycle mode check: if Greenfield (no code), allow executing Wave 0 scaffolding tasks and bootstrapping with explicit human approval. Prohibit bug fixes.
3. server-memory (MANDATORY): load Decisions, Conventions, Corrections, BugFixes → report "🧠 Memoria: ..."
4. codebase-memory (MANDATORY): verify index, index/re-index if missing or stale → report "🗺️ Grafo: ..."
5. If AB# in context, read WI from ADO automatically
6. Check for active QA corte (PBIs with 'corte al' in title, state=Acceptance)
7. Detect type: Feature → design + tasks. Bug → bug-fix-protocol. QA Corte → prioritize corte bugs.
8. Detect phase of work and proceed

## Feature flow
1. Detect entry point:
   - Search for docs/requirements/functional-packages/Functional-Package-HU-{id}-*.md
   - If found → Functional Package flow (PRIMARY)
   - If not found → ADO WI flow (FALLBACK)

### Functional Package flow (PRIMARY)
1. Read Functional Package → scope, acceptance criteria, BR, DD, E2E, Test, Implementation Contract
   - READ-ONLY — NEVER edit the Functional Package
   - Respect Implementation Contract
   - If ambiguity → STOP → Functional Escalation Protocol
2. PROPOSE: create branch → wait for approval
3. Create branch, move WI to In Progress
4. PROPOSE: create requirements.md referencing Functional Package → wait for approval
5. Create specs/AB#id/requirements.md (link to package, not copy)
6. PROPOSE: create design.md → wait for approval
7. Create specs/AB#id/design.md (template)
8. PROPOSE: create tasks.md → wait for approval
9. Create specs/AB#id/tasks.md (template)
10. For each task: PROPOSE → wait → execute → code → lint → tests → commit
11. PROPOSE: create PR → wait for approval
12. Create PR, link WI, move WI to Fixed

### ADO WI flow (FALLBACK)
1. Read WI from ADO → requirement + linked WIs
2. PROPOSE: create branch → wait for approval
3. Create branch, move WI to In Progress
4. PROPOSE: create requirements.md from WI → wait for approval
5. Create specs/AB#id/requirements.md (template, copy WI content)
6-13. Same as Functional Package flow steps 6-12

## Bug flow (activate skill bug-fix-protocol — evidence required)
A bug is NOT fixed until there is evidence. NEVER declare "fixed" based on reasoning alone.
1. Investigate BEFORE touching code: ADO WI + repro steps + linked WIs + resolved Bugs in same module; server-memory search_nodes (Corrections, BugFixes); codebase-memory search_graph + get_code_snippet; git log / git blame (regression?)
2. PROPOSE: create branch fix/AB#id-description → wait for approval
3. Create branch, move WI to In Progress
4. Reproduce: failing test (unit, or Playwright for UI). Cannot reproduce → STOP and ask
5. Impact: codebase-memory trace_path inbound → callers, affected features, risk BAJO/MEDIO/ALTO → present BEFORE fixing
6. Fix: PROPOSE minimal root-cause diff → wait for approval → implement. No refactoring
7. Verify: test passes + module suite + lint; callers tests if MEDIO/ALTO; local smoke test with Playwright against the running app (environments.local: repro steps + affected screens); acceptance criteria
8. Evidence report in PR body → PROPOSE PR → wait for approval
9. Create PR, link WI, move WI to Fixed
10. Deployment verification: DEV after merge to develop; QA after release/corte merged to qa (branch contains commit, pipeline OK, env parity, smoke test)
11. Write BugFix to server-memory (+ Correction if regression)
If QA reopens: write Correction to server-memory, restart from step 1

## QA Corte flow (bugs from active testing cut)
See qa-corte-workflow skill for full detection rules, release strategy, and audit trail.

1. Detect active corte → query ADO for PBIs matching the corte pattern
2. Show corte summary: PBIs, pending bugs (To Do / In Progress / Fixed), HU/E2E status
3. Prioritize corte bugs over features — suggest them first, human decides
4. For each corte bug: follow standard Bug flow above (no design, no tasks)
5. After all corte bugs are Fixed → notify: "All bugs from corte are Fixed. Waiting for QA."
6. Release to QA (when human requests it):
   - Audit develop vs corte scope (commit-by-commit)
   - NEVER merge develop→qa directly — always create release/corte-DD-MM-YYYY branch
   - Create surgical release branch from origin/qa with only scoped fixes
   - PROPOSE PR: release/corte-DD-MM-YYYY → qa — wait for approval
   - Post audit trail comment on ADO PBIs
   - Human merges (Gate 4)
7. Resume normal feature/bug flow

## Production release flow (qa → prod)
See qa-corte-workflow skill §Production release flow for full details.

1. Audit qa vs prod scope — list certified cortes, exclude cortes still in testing
2. Create surgical branch: release/prod-DD-MM-YYYY from origin/main
3. Bring ONLY certified work from qa
4. Determine version: read latest git tag, propose semver bump (minor for corte, patch for hotfix)
5. Update VERSION file if enabled in .sdd-config.json
6. PROPOSE PR: release/prod-DD-MM-YYYY → main — wait for approval
7. Human merges (Gate 3 + Gate 4 — agent NEVER merges to prod)
8. After merge: tag vX.Y.Z, push tags, move WIs to Done in ADO, post audit comment
9. Sync branches: merge main → develop to keep in sync

## After finishing an AB#
- Read Azure DevOps → check for remaining assigned items
- If items remain: present them and ask to continue
- DO NOT say goodbye without offering remaining work

## Rules
- DO NOT execute without approval
- DO NOT auto-deploy to prod
- DO NOT mix features
- DO NOT create specs without templates
- DO NOT create design.md/tasks.md for bugs
- DO NOT edit protected files (.agents/mcp_config.json, .sdd-config.json, .sdd-credentials.json, etc.)
- DO NOT move WI to Done, In Testing, Reopen, On Hold, Fix Later, Acceptance, Test Passed, or QA Passed
- Every commit must reference AB#
- git push requires approval

## Permissions
- commandExecutionPolicy: eager (execute with approval)
- git push: ask
BUILD_EOF

echo "   OK 3 agents generated (sdd-router, sdd-plan, sdd-build)"

echo "   OK Antigravity (.agents/) structure generated"
