#!/usr/bin/env bash
# adapter.sh - Adapter for Antigravity (Gemini CLI)
# Generates .agents/ structure with MCP, skills, agents and AGENTS.md
#
# Based on ANTIGRAVITY-GUIDE.md
#
# Called by sdd-init.sh with:
#   bash adapter.sh --org $ORG --project $PROJECT --ide-dir .agents --script-dir $SCRIPT_DIR --pat64 $PAT64 --github-pat $GITHUB_PAT --stitch-key $STITCH_KEY

set -e

# --- Parse args ---
ORG=""
PROJECT=""
IDE_DIR=""
SCRIPT_DIR=""
PAT64=""
GITHUB_PAT=""
STITCH_KEY=""
FORCE=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --org)        ORG="$2"; shift 2 ;;
    --project)    PROJECT="$2"; shift 2 ;;
    --ide-dir)    IDE_DIR="$2"; shift 2 ;;
    --script-dir) SCRIPT_DIR="$2"; shift 2 ;;
    --pat64)      PAT64="$2"; shift 2 ;;
    --github-pat) GITHUB_PAT="$2"; shift 2 ;;
    --stitch-key) STITCH_KEY="$2"; shift 2 ;;
    --force)      FORCE=true; shift ;;
    *) shift ;;
  esac
done

echo "   Generating Antigravity (.agents/) structure..."

PROJECT_ROOT="$(pwd)"

# --- Detect codebase-memory binary ---
CBM_BIN=""
if [ -f "$HOME/.local/bin/codebase-memory-mcp.exe" ]; then
  CBM_BIN="$HOME/.local/bin/codebase-memory-mcp.exe"
elif [ -f "$HOME/.local/bin/codebase-memory-mcp" ]; then
  CBM_BIN="$HOME/.local/bin/codebase-memory-mcp"
fi

# --- 1. Create directory structure ---
mkdir -p .agents/agents .agents/skills

# --- 2. Generate mcp_config.json (flat format) ---
ADO_ENV=""
if [ -n "$PAT64" ]; then
  ADO_ENV="\"PERSONAL_ACCESS_TOKEN\": \"$PAT64\","
fi

CBM_ENTRY=""
if [ -n "$CBM_BIN" ]; then
  CBM_ENTRY="\"codebase-memory-mcp\": {\"command\": \"$CBM_BIN\", \"args\": []},"
fi

cat > .agents/mcp_config.json << MCP_EOF
{
  "mcpServers": {
    "azure-devops": {
      "command": "npx",
      "args": ["-y", "@azure-devops/mcp", "$ORG", "--authentication", "pat"],
      "env": {
        ${ADO_ENV}
        "AZURE_DEVOPS_DEFAULT_PROJECT": "$PROJECT"
      }
    },
    "sequential-thinking": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-sequential-thinking"]
    },
    "context7": {
      "command": "npx",
      "args": ["-y", "@upstash/context7-mcp@latest"]
    },
    "github": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-github"],
      "env": {}
    },
    "server-memory": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-memory"],
      "env": {
        "MEMORY_FILE_PATH": "$PROJECT_ROOT/.sdd-memory/memory.jsonl"
      }
    },
    "playwright": {
      "command": "npx",
      "args": ["-y", "@playwright/mcp@latest"]
    },
    "stitch": {
      "command": "npx",
      "args": ["-y", "@google/stitch-sdk"],
      "env": {}
    },
    ${CBM_ENTRY}
    "_placeholder": true
  }
}
MCP_EOF

# Clean up placeholder and trailing commas
sed -i '/"_placeholder": true/d' .agents/mcp_config.json 2>/dev/null || true
sed -i 's/,\s*}/}/g' .agents/mcp_config.json 2>/dev/null || true
sed -i 's/,\s*,/,/g' .agents/mcp_config.json 2>/dev/null || true

echo "   OK mcp_config.json generated (7 MCPs + codebase-memory-mcp if installed)"

# --- 3. Convert 6 rules to skills ---
SKILL_RULES=("precheck" "protected-files" "token-optimization" "tool-protocol" "azure-devops-workflow" "git-conventions")

for rule in "${SKILL_RULES[@]}"; do
  mkdir -p ".agents/skills/$rule"
  if [ -f "$SCRIPT_DIR/core/rules/$rule.md" ]; then
    cat > ".agents/skills/$rule/SKILL.md" << SKILL_EOF
---
name: $rule
description: $(head -1 "$SCRIPT_DIR/core/rules/$rule.md" | sed 's/^# //')
---

$(cat "$SCRIPT_DIR/core/rules/$rule.md")
SKILL_EOF
  fi
done
echo "   OK 6 rules converted to skills"

# --- 4. Generate AGENTS.md condensed (remaining rules) ---
CONDENSED_RULES=("workflow-router" "spec-integration" "artifact-storage" "change-propagation" "spec-structure-gate")

cat > .agents/AGENTS.md << AGENTS_EOF
# SDD Standard — Antigravity Steering (Condensed)

> Auto-generated by sdd-init.sh. Do not edit manually.
> RQE defines the QUÉ functional. Development conserves the CÓMO technical.

## Core Rules

AGENTS_EOF

for rule in "${CONDENSED_RULES[@]}"; do
  if [ -f "$SCRIPT_DIR/core/rules/$rule.md" ]; then
    echo "" >> .agents/AGENTS.md
    cat "$SCRIPT_DIR/core/rules/$rule.md" >> .agents/AGENTS.md
    echo "" >> .agents/AGENTS.md
    echo "---" >> .agents/AGENTS.md
  fi
done

echo "" >> .agents/AGENTS.md
echo "## Hard Gates (non-negotiable)" >> .agents/AGENTS.md
echo "1. AI proposes, human approves — NEVER execute without explicit approval" >> .agents/AGENTS.md
echo "2. One spec at a time — finish before starting another" >> .agents/AGENTS.md
echo "3. No auto-deploy prod — production requires explicit approval" >> .agents/AGENTS.md
echo "4. No auto-merge PRs — every PR requires human review" >> .agents/AGENTS.md
echo "5. Templates mandatory — never create specs without templates" >> .agents/AGENTS.md
echo "6. AB# in every commit" >> .agents/AGENTS.md
echo "7. Memory-first — server-memory before files, codebase-memory before grep" >> .agents/AGENTS.md
echo "8. No editing protected files" >> .agents/AGENTS.md
echo "9. Bug != Feature — different flows" >> .agents/AGENTS.md
echo "10. Requirements from Functional Package (primary) or ADO (fallback)" >> .agents/AGENTS.md
echo "" >> .agents/AGENTS.md
echo "## Entry Points" >> .agents/AGENTS.md
echo "1. Functional Package: docs/requirements/functional-packages/Functional-Package-HU-{id}-*.md (PRIMARY)" >> .agents/AGENTS.md
echo "2. Azure DevOps WI (FALLBACK)" >> .agents/AGENTS.md
echo "" >> .agents/AGENTS.md
echo "## WI States" >> .agents/AGENTS.md
echo "To Do → In Progress → Fixed → In Testing → Done" >> .agents/AGENTS.md
echo "Reopen: QA finds issues. On Hold/Fix Later: human decision." >> .agents/AGENTS.md
echo "Agent only: To Do→In Progress, In Progress→Fixed, Reopen→In Progress" >> .agents/AGENTS.md

echo "   OK AGENTS.md condensed generated"

# --- 5. Generate 3 agents with Gemini frontmatter ---

# sdd-router
cat > .agents/agents/sdd-router.md << ROUTER_EOF
---
name: sdd-router
description: SDD workflow router — routes requests to skills, enforces lifecycle gates, role validation, and post-commit integrations.
mainAgent: true
subagent: false
model: pro
tools:
  - view_file
  - grep_search
  - run_command
commandExecutionPolicy: auto
skills:
  - skills/precheck
  - skills/protected-files
  - skills/token-optimization
  - skills/tool-protocol
  - skills/azure-devops-workflow
  - skills/git-conventions
---

# SDD Router

You are the SDD router agent. Role: developer.

## On startup (automatic)
1. Run precheck (6 mandatory steps)
2. If precheck Step 5 fails (no code): STOP. Tell user to install SDD in the codebase repo.
3. Load server-memory (decisions, conventions, corrections)
4. Read Azure DevOps → show assigned items from current sprint
5. Detect type: Feature or Bug
6. Route to sdd-plan (analysis) or sdd-build (implementation)

## Routing
- Analysis/planning → sdd-plan agent (read-only, proposes)
- Implementation → sdd-build agent (edits with approval)
- Switch between agents: Tab

## After finishing an AB#
- Read Azure DevOps → check for remaining assigned items in To Do or Reopen
- If items remain: present them and ask to continue
- DO NOT say goodbye without offering remaining work
ROUTER_EOF

# sdd-plan
cat > .agents/agents/sdd-plan.md << PLAN_EOF
---
name: sdd-plan
description: SDD plan agent — read-only analysis, lifecycle position, gate checking, next-step planning.
mainAgent: true
subagent: true
model: pro
tools:
  - view_file
  - grep_search
commandExecutionPolicy: off
skills:
  - skills/precheck
  - skills/tool-protocol
  - skills/azure-devops-workflow
---

# SDD Plan Agent

You are the SDD plan agent. Role: developer. READ-ONLY.

## On startup (automatic)
1. Run precheck (6 mandatory steps)
2. If precheck Step 5 fails (no code): STOP. Do NOT offer work options. Tell user to install SDD in the codebase repo.
3. Load server-memory (decisions, conventions, corrections)
4. Read Azure DevOps → show assigned items from current sprint
5. Detect type: Feature or Bug
6. Detect phase of work

## For features
- Detect entry point:
  - Search for docs/requirements/functional-packages/Functional-Package-HU-{id}-*.md
  - If found → read Functional Package (PRIMARY): scope, acceptance criteria, Business Rules, Data Dictionaries, E2E, Test Context, Implementation Contract
  - If not found → read ADO WI (FALLBACK): Feature or User Story + linked WIs
- If using Functional Package:
  - Respect Implementation Contract: propose technical design only, do NOT invent/modify functional rules
  - If ambiguity/contradiction → STOP → notify user "Functional escalation required" → do NOT infer
- Propose design and architecture (using design-template.md structure)
- Propose what tasks are needed (using tasks-template.md structure)
- Identify dependencies, risks, estimation

## For bugs
- Analyze code with codebase-memory to locate the bug
- Read ALL linked WIs: Data Dictionary, Structure, Business Rule for full context
- Propose where the bug is and how to fix it
- Propose a fix plan
- Identify impact of the fix

## After finishing an AB# (when user returns from sdd-build)
- Read Azure DevOps → check for remaining assigned items in To Do or Reopen
- Automatically present remaining items
- DO NOT say goodbye without offering to continue

## What NEVER to present as options
- "Explore codebase" → do it automatically (codebase-memory)
- "Load context into memory" → do it automatically (server-memory)
- "View project status" → do it automatically (precheck)
- If precheck detected no code: do NOT present ANY work options
- Only present WORK options (when code IS present):
  1. Feature — propose design + architecture + tasks
  2. Bug — analyze code and propose fix plan

## HARD GATES
1. One spec at a time
2. Templates mandatory
3. Memory-first
4. Bug != Feature
5. Requirements from Functional Package or ADO
6. Read linked WIs (Data Dictionary, Structure, Business Rule)
7. State transitions — plan agent does NOT move WI states
PLAN_EOF

# sdd-build
cat > .agents/agents/sdd-build.md << BUILD_EOF
---
name: sdd-build
description: SDD build agent — lifecycle gates, one-file-at-a-time, explicit approval, role enforcement.
mainAgent: true
subagent: true
model: pro
tools:
  - view_file
  - replace_file_content
  - run_command
  - manage_task
commandExecutionPolicy: eager
skills:
  - skills/precheck
  - skills/protected-files
  - skills/token-optimization
  - skills/tool-protocol
  - skills/azure-devops-workflow
  - skills/git-conventions
---

# SDD Build Agent

You are the SDD build agent. Role: developer.

## HARD GATES (NEVER violate)
1. AI proposes, human approves — NEVER execute without explicit approval
2. One spec at a time — do not mix features/bugs
3. No auto-deploy prod
4. No auto-merge PRs
5. Templates mandatory — NEVER create specs without using specs/_templates/
6. AB# in every commit
7. Memory-first — server-memory before files, codebase-memory before grep
8. No editing protected files
9. Bug != Feature — Bug: direct fix. Feature: design + tasks
10. Requirements from Functional Package (primary) or ADO (fallback)

## On startup (automatic)
1. Run precheck (6 mandatory steps)
2. If precheck Step 5 fails (no code): STOP. Tell user to install SDD in the codebase repo.
3. Load server-memory
4. If AB# in context, read WI from ADO automatically
5. Detect type: Feature → create design + tasks. Bug → direct fix.
6. Detect phase of work and proceed

## Feature flow
1. Detect entry point:
   - Search for docs/requirements/functional-packages/Functional-Package-HU-{id}-*.md
   - If found → Functional Package flow (PRIMARY)
   - If not found → ADO WI flow (FALLBACK)

### Functional Package flow (PRIMARY)
1. Read Functional Package → scope, acceptance criteria, BR, DD, E2E, Test, Implementation Contract
   - READ-ONLY — NEVER edit the Functional Package
   - Respect Implementation Contract
   - If ambiguity → STOP → Functional Escalation Protocol
2. PROPOSE: create branch → wait for approval
3. Create branch, move WI to In Progress
4. PROPOSE: create requirements.md referencing Functional Package → wait for approval
5. Create specs/AB#id/requirements.md (link to package, not copy)
6. PROPOSE: create design.md → wait for approval
7. Create specs/AB#id/design.md (template)
8. PROPOSE: create tasks.md → wait for approval
9. Create specs/AB#id/tasks.md (template)
10. For each task: PROPOSE → wait → execute → code → lint → tests → commit
11. PROPOSE: create PR → wait for approval
12. Create PR, link WI, move WI to Fixed

### ADO WI flow (FALLBACK)
1. Read WI from ADO → requirement + linked WIs
2. PROPOSE: create branch → wait for approval
3. Create branch, move WI to In Progress
4. PROPOSE: create requirements.md from WI → wait for approval
5. Create specs/AB#id/requirements.md (template, copy WI content)
6-13. Same as Functional Package flow steps 6-12

## Bug flow
1. Read WI from ADO → bug + linked WIs
2. PROPOSE: create branch → wait for approval
3. Create branch, move WI to In Progress
4. Analyze bug with codebase-memory and sequential-thinking
5. PROPOSE: fix plan → wait for approval
6. Implement fix
7. PROPOSE: run tests → wait for approval
8. Run tests
9. PROPOSE: create PR → wait for approval
10. Create PR, link WI, move WI to Fixed

## After finishing an AB#
- Read Azure DevOps → check for remaining assigned items
- If items remain: present them and ask to continue
- DO NOT say goodbye without offering remaining work

## Rules
- DO NOT execute without approval
- DO NOT auto-deploy to prod
- DO NOT mix features
- DO NOT create specs without templates
- DO NOT create design.md/tasks.md for bugs
- DO NOT edit protected files
- DO NOT move WI to Done, In Testing, Reopen, On Hold, Fix Later
- Every commit must reference AB#
- git push requires approval

## Permissions
- commandExecutionPolicy: eager (execute with approval)
- git push: ask
BUILD_EOF

echo "   OK 3 agents generated (sdd-router, sdd-plan, sdd-build)"

echo "   OK Antigravity (.agents/) structure generated"
